### ISSUE TITLE
Not compatible with MySQL without this fix

### ISSUE THREAD

**Issue by ngardner** [10111282/yii2-sortable#1]
Due to MySQL's inability to use the same table name in the WHERE clause for UPDATE queries, the rebuildSortAfter method fails on MySQL.

I fixed this, by updating the subQuerySortVal and subQueryGroupId to always be actual values instead of Query objects, like this...

`$subQuerySortVal = (new Query())->select($this->srtColumn.' as sort_column')->from($this->targetTable)->where([$this->pkColumn => $afterId])->one()['sort_column'];`

**Comment by 10111282** [comment]
Thanks for pointing out this issue. Fixed in the version 1.2.2.
Now it's possible to specify the database you are using
`'databaseDriver' => serj\sortable\Sortable::DB_DRIVER_MYSQL`
